config/routes.rb
Rails.application.routes.draw do
  get "flowers/index"
  get "flowers/new"
  get "flowers/show"
  get "flowers/edit"
  resources :flowers
  scope "(:locale)", locale: /en|vi/ do
    root to: "static_pages#home"
    get "/product", to: "static_pages#product"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flower.rb
class Flower < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  mount_uploader :image, ImageUploader
  validates :name, presence: true, uniqueness: true
  validates :image, :price, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 1.0}
  validates :image, format: {with: /\.(gif|jpg|png|jpeg)\Z/i,
                             message: "Chi nhan file GIF, JPG, PNG, JPEG"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    {locale: I18n.locale}
  end
end

app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
  before_action :find_flower, only: [:show, :edit, :update, :destroy]

  def index
    @flowers = Flower.all.oder("create_at DESC")
  end

  def new
    @flower = Flower.new
  end

  def create
    @flower = Flower.new flower_params
    if @flower.save
      # flash[:success] = t ".flash"
      redirect_to index_flower_path
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @flower.update(flower_params)
      redirect_to flower_path(@flower)
    else
      render "edit"
    end
  end

  def destroy
    @flower.destroy
    redirect_to index_flower_path
  end

  private

  def flower_params
    params.require(:flower).permit :name, :description, :image, :price, :discount
  end

  def find_flower
    @flower = Flower.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t :base_title
    page_title.empty? ? base_title : page_title + " | " + base_title
  end
end

app/views/flowers/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @flower do |f| %>

      <%= f.label :name, t(".name") %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :description, t(".description") %>
      <%= f.text_field :description, class: "form-control" %>

      <%= f.label :image, t(".image") %>
      <%= f.file_field :image, accept: Settings.accept, class: "form-control" %>

      <%= f.label :price, t(".price") %>
      <%= f.text_field :price, class: "form-control" %>

      <%= f.label :discount, t(".discount") %>
      <%= f.text_field :discount, class: "form-control" %>

      <%= f.submit t(".submit"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/flowers/edit.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".h1" %></h1>

<%= render "form" %>

app/views/flowers/index.html.erb
<% provide :title, t(".title") %>

<% @flower.each do |flower| %>
   <%= link to  flower.name, flower_path(flower) %>
<% end %>

<%= link to  t(".add"), new_flower_path %>

app/views/flowers/new.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".h1" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @flower do |f| %>

      <%= f.label :name, t(".name") %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :description, t(".description") %>
      <%= f.text_field :description, class: "form-control" %>

      <%= f.label :image, t(".image") %>
      <%= f.file_field :image, accept: Settings.accept, class: "form-control" %>

      <%= f.label :price, t(".price") %>
      <%= f.text_field :price, class: "form-control" %>

      <%= f.label :discount, t(".discount") %>
      <%= f.text_field :discount, class: "form-control" %>

      <%= f.submit t(".submit"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/flowers/show.html.erb
<% provide :title, @flower %>
<h1><%= t".h1" %></h1>

<%= @flower.name %>
<%= sanitize(@flower.description) %>
<%= image_tag flower.image.url if flower.image? %>
<%= @flower.price %>
<%= @flower.discount %>

<%= link_to t(".back"), index_flower_path(@flower) %>
<%= link_to t(".edit"), edit_flower_path(@flower) %>
<%= link_to t(".delete)", flower_path(@flower), method: :delete, data: { confirm: t(".confirm")} %>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small stylish-color-dark pt-4">
  <!-- <div class="container"> -->
    <div class="box-html">
      <div class="policy-content clearfix">
        <div class="col-md-3  clearfix">
          <div class="sale-policy-block">
            <i class="fa fa-refresh"></i>
            <span><%= t ".repay" %></span>
          </div>
        </div>
        <div class="col-md-3 clearfix">
          <div class="sale-policy-block">
            <i class="fa fa-truck"></i>
            <span><%= t ".ship" %></span>
          </div>
        </div>
        <div class="col-md-3 clearfix">
          <div class="sale-policy-block">
            <i class="fa fa-life-saver"></i>
            <span><%= t ".payment" %></span>
          </div>
        </div>
        <div class="col-md-3 clearfix">
          <div class="sale-policy-block">
            <i class="fa fa-users"></i>
            <span><%= t ".support" %></span>
          </div>
        </div>
      </div>
    </div>
 <!--  </div> -->
 <!-- Footer Links -->
  <div class="container text-center text-md-left">
    <!-- Grid row -->
    <div class="row">
      <!-- Grid column -->
      <div class="col-md-4 mx-auto">
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4"><%= t ".aboutus" %></h5>
        <p>...</p>
      </div>

      <!-- Grid column -->
      <div class="col-md-4 mx-auto">
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4"><%= t ".address" %></h5>
        <ul class="list-unstyled">
          <li>Km10,Nguyen Trai, Ha Dong, Ha Noi</li>
          <li>Email:flowershop@gmail.com</li>
          <li>Phone:0123456789</li>
        </ul>
      </div>

      <!-- Grid column -->
      <div class="col-md-2 mx-auto">
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4"><%= t ".policy" %></h5>
        <ul class="list-unstyled">
          <li>
            <%= link_to t(".guarantee"), "#" %>
          </li>
        </ul>
      </div>

      <!-- Grid column -->
      <div class="col-md-2 mx-auto">
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4"><%= t ".social" %></h5>
        <ul class="list-unstyled">
         <!-- Social buttons -->
          <ul class="list-unstyled list-inline text-center">
            <li class="list-inline-item">
              <%= link_to "#", class: "btn-floating btn-fb mx-1" do %>
                <i class="fa fa-facebook"></i>
              <% end %>
            </li>
            <li class="list-inline-item">
              <%= link_to "#", class: "btn-floating btn-fb mx-1" do %>
                <i class="fa fa-twitter"></i>
              <% end %>
            </li>
            <li class="list-inline-item">
              <%= link_to "#", class: "btn-floating btn-fb mx-1" do %>
                <i class="fa fa-google-plus"></i>
              <% end %>
            </li>
          </ul>
        <!-- Social buttons -->
        </ul>
      </div>
    </div>
    <!-- Grid row -->
    <hr class="clearfix w-100 d-md-none">
    <!-- Call to action -->
    <ul class="list-unstyled list-inline text-center py-2">
      <li class="list-inline-item">
        <h5 class="mb-1"><%= t ".register" %></h5>
      </li>
      <li class="list-inline-item">
        <%= link_to t(".signup"), "#", class: "btn btn-danger btn-rounded" %>
      </li>
    </ul>
    <!-- Call to action -->
    <hr class="clearfix w-100 d-md-none">
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2018 Copyright:
      <%= link_to "Flowershop.com.vn", root_path %>
    </div>
    <!-- Copyright -->
  </div>
</footer>
<!-- Footer -->

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
            aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
          <%=link_to( image_tag("logo.jpg", size: "60"),
            root_path, class: "navbar-brand logo_img") %>
          <p class="logo">Flower Shop</p>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to t(".home"), root_path %>
              <span class="sr-only">(current)</span>
            </li>
            <li class="dropdown">
              <%= link_to "#", class: "dropdown-toggle",
                data: {toggle: "dropdown"}, role: "button",
                aria: {haspopup: "true", expanded: "false"} do %>
                  <%= t(".product") %><b class="caret"></b>
              <% end %>
              <ul class="dropdown-menu">
                <li><%= link_to "Something", product_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Something", product_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Something", product_path %></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to t(".add"), new_flower_path %></li>
            <li class="dropdown">
              <%= link_to "#", class: "dropdown-toggle",
                data: {toggle: "dropdown"}, role: "button",
                aria: {haspopup: "true", expanded: "false"} do %>
                  <%= t(".account") %><b class="caret"></b>
              <% end %>
              <ul class="dropdown-menu">
                <li><%= link_to t(".account"), "#" %></li>
                <li><%= link_to t(".setting"), "#" %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to t(".logout"), "#" %></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <p>
        <%= link_to "English", locale:"en" %>
        <%= link_to "Vietnamese", locale:"vi" %>
      </p>
      <h1><%= yield :h1_tag %></h1>
    <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/static_pages/home.html.erb
<% provide :title, t(".title") %>
<% provide :h1_tag, t(".h1_tag") %>
<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag("anh1.jpg") %>
      <div class="caption">
        <h3>...</h3>
        <p>...</p>
        <p>
          <%= link_to t(:details), "#", class: "btn btn-primary", role: "button" %>
          <%= link_to t(:addcart), "#", class: "btn btn-default", role: "button" %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/product.html.erb
<% provide :title, t(".title") %>
<% provide :h1_tag, t(".h1_tag") %>